# Project Name
# Database Configuration (MySql)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ notes_db #${DATABASE_URL}
    username: user #${DATABASE_USERNAME}
    password: 1234asdf #${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false